import type { FileNode, FileChange } from "./types"

export function createFileNode(
  name: string,
  type: "file" | "folder",
  path: string,
  content?: string,
  language?: string,
): FileNode {
  return {
    id: generateId(),
    name,
    type,
    path,
    content,
    language,
    children: type === "folder" ? [] : undefined,
  }
}

export function generateId(): string {
  return `${Date.now()}-${Math.random().toString(36).substr(2, 9)}`
}

export function findNodeByPath(files: FileNode[], path: string): FileNode | null {
  const parts = path.split("/").filter(Boolean)
  let current: FileNode[] = files

  for (let i = 0; i < parts.length; i++) {
    const part = parts[i]
    const node = current.find((n) => n.name === part)

    if (!node) return null

    if (i === parts.length - 1) return node

    if (node.type === "folder" && node.children) {
      current = node.children
    } else {
      return null
    }
  }

  return null
}

export function addFileToTree(files: FileNode[], path: string, content: string, language: string): FileNode[] {
  const parts = path.split("/").filter(Boolean)
  const newFiles = JSON.parse(JSON.stringify(files)) as FileNode[]

  let current = newFiles
  let currentPath = ""

  for (let i = 0; i < parts.length; i++) {
    const part = parts[i]
    currentPath = currentPath ? `${currentPath}/${part}` : part

    const isLastPart = i === parts.length - 1
    const existingNode = current.find((n) => n.name === part)

    if (existingNode) {
      if (isLastPart && existingNode.type === "file") {
        // Update existing file
        existingNode.content = content
        existingNode.language = language
      } else if (!isLastPart && existingNode.type === "folder" && existingNode.children) {
        current = existingNode.children
      }
    } else {
      if (isLastPart) {
        // Create new file
        current.push(createFileNode(part, "file", currentPath, content, language))
      } else {
        // Create new folder
        const newFolder = createFileNode(part, "folder", currentPath)
        current.push(newFolder)
        current = newFolder.children!
      }
    }
  }

  return sortFileTree(newFiles)
}

export function deleteFileFromTree(files: FileNode[], path: string): FileNode[] {
  const parts = path.split("/").filter(Boolean)
  const newFiles = JSON.parse(JSON.stringify(files)) as FileNode[]

  if (parts.length === 1) {
    return newFiles.filter((n) => n.name !== parts[0])
  }

  const parentPath = parts.slice(0, -1).join("/")
  const fileName = parts[parts.length - 1]
  const parent = findNodeByPath(newFiles, parentPath)

  if (parent && parent.type === "folder" && parent.children) {
    parent.children = parent.children.filter((n) => n.name !== fileName)
  }

  return newFiles
}

export function applyFileChanges(files: FileNode[], changes: FileChange[]): FileNode[] {
  let result = files

  for (const change of changes) {
    switch (change.action) {
      case "create":
      case "update":
        result = addFileToTree(result, change.path, change.content || "", change.language || "plaintext")
        break
      case "delete":
        result = deleteFileFromTree(result, change.path)
        break
    }
  }

  return result
}

export function sortFileTree(files: FileNode[]): FileNode[] {
  return files
    .sort((a, b) => {
      // Folders first
      if (a.type === "folder" && b.type === "file") return -1
      if (a.type === "file" && b.type === "folder") return 1
      // Then alphabetically
      return a.name.localeCompare(b.name)
    })
    .map((node) => ({
      ...node,
      children: node.children ? sortFileTree(node.children) : undefined,
    }))
}

export function getDefaultProject(): FileNode[] {
  return sortFileTree([
    createFileNode("src", "folder", "src", undefined, undefined),
    createFileNode(
      "package.json",
      "file",
      "package.json",
      JSON.stringify(
        {
          name: "my-app",
          version: "1.0.0",
          private: true,
          scripts: {
            dev: "next dev",
            build: "next build",
            start: "next start",
          },
          dependencies: {
            next: "^14.0.0",
            react: "^18.2.0",
            "react-dom": "^18.2.0",
          },
          devDependencies: {
            typescript: "^5.0.0",
            "@types/react": "^18.2.0",
            "@types/node": "^20.0.0",
          },
        },
        null,
        2,
      ),
      "json",
    ),
    createFileNode("README.md", "file", "README.md", "# My App\n\nGenerated by Aurora AI Builder", "markdown"),
  ])
}

export function flattenFileTree(files: FileNode[]): { path: string; content: string }[] {
  const result: { path: string; content: string }[] = []

  function traverse(nodes: FileNode[]) {
    for (const node of nodes) {
      if (node.type === "file" && node.content) {
        result.push({ path: node.path, content: node.content })
      } else if (node.type === "folder" && node.children) {
        traverse(node.children)
      }
    }
  }

  traverse(files)
  return result
}
